#!/usr/bin/env bash
#209.133.111.211 - - [10/Feb/2016:19:53:16 -0800] "GET /robots.txt HTTP/1.1" 200 367 "-" "python-requests/2.2.1 CPython/2.7.3 Linux/3.2.0-56-generic"
awk '{print $1,$9}' apache-access.log
