#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:

count=0
name="Best School"

while [ $count -lt 10 ]
do
	if [[ $count -eq 3 ]];
	then
		echo "bad luck"
	elif [[ $count -eq 7 ]];
	then
		echo "good luck"
	else
		echo "$name"
	fi
	((count++))	
done
